### ISSUE TITLE
How did you set the parameters when data normalizing the data?

### ISSUE THREAD

**Issue by skek0624** [acecreamu/angularGAN#1]
How did you set it up? 

(In general, Imagenet dataset parameter : 
normalize = torchvision.transforms.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225) )  )

and you set this parameter(unaligned_dataset.py : 
tmp = A[0, ...] * 0.299 + A[1, ...] * 0.587 + A[2, ...] * 0.114 # RGB to gray
tmp = B[0, ...] * 0.299 + B[1, ...] * 0.587 + B[2, ...] * 0.114

**Comment by acecreamu** [comment]
Hi, the think you copied is to transform RGB to grayscale if you specify usage of grayscale images in options.

The normalization you are asking about is in `data/base_dataset.py` lines 48-50:
```
                       transform_list += [transforms.ToTensor(),
                       transforms.Normalize((0.5, 0.5, 0.5),
                                            (0.5, 0.5, 0.5))]
```
